package ru.nortti.filmssearch

object FilmData {

    fun getFilms() = listOf(
        Film("Pulp Fiction","poster_01","Jules Winnfield and Vincent Vega are two hitmen out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. Honey Bunny and Pumpkin are a couple of young lovers and small time thieves who decide they need a change of venue. The lives of these seemingly unrelated people are woven together in a wildly entertaining and exhilarating motion picture adventure that both thrills and amuses."),
        Film("Interstellar","poster_02","Cooper, an ex-engineer, currently growing corn on his farm, asked to be a part of the interstellar group of researchers, and aid them in their quest of finding habitable planet, so that they could move there and save the human race from extinction."),
        Film("Beetlejuice","poster_04", "Thanks to an untimely demise via drowning, a young couple end up as poltergeists in their New England farmhouse, where they fail to meet the challenge of scaring away the insufferable new owners, who want to make drastic changes. In desperation, the undead newlyweds turn to an expert frightmeister, but he’s got a diabolical agenda of his own."),
        Film("Back to the Future","poster_06", "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents’ first meeting and attracting his mother’s romantic interest. Marty must repair the damage to history by rekindling his parents’ romance and – with the help of his eccentric inventor friend Doc Brown – return to 1985."),
        Film("Jaws","poster_08", "An insatiable great white shark terrorizes the townspeople of Amity Island, The police chief, an oceanographer and a grizzled shark hunter seek to destroy the bloodthirsty beast."),
        Film("The Fifth Element","poster_09","In 2257, a taxi driver is unintentionally given the task of saving a young girl who is part of the key that will ensure the survival of humanity."),
        Film("The Mask","poster_14","When timid bank clerk Stanley Ipkiss (Jim Carrey) discovers a magical mask containing the spirit of the Norse god Loki, his entire life changes. While wearing the mask, Ipkiss becomes a supernatural playboy exuding charm and confidence which allows him to catch the eye of local nightclub singer Tina Carlyle (Cameron Diaz). Unfortunately, under the mask’s influence, Ipkiss also robs a bank, which angers junior crime lord Dorian Tyrell (Peter Greene), whose goons get blamed for the heist."),
        Film("Leon","poster_15", "Leon, the top hit man in New York, has earned a rep as an effective “cleaner”. But when his next-door neighbors are wiped out by a loose-cannon DEA agent, he becomes the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda’s thoughts turn to revenge, and she considers following in Leon’s footsteps."),
        Film("Fight Club","poster_17", "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground “fight clubs” forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion."),
        Film("Dracula","poster_23", "When Dracula leaves the captive Jonathan Harker and Transylvania for London in search of Mina Harker — the spitting image of Dracula’s long-dead wife, Elisabeta — obsessed vampire hunter Dr. Van Helsing sets out to end the madness.")
    )
}